// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLink = `-- name: CreateLink :one

INSERT INTO link (
    user_id, code, original_url, custom_alias, expires_at, is_active, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, code, original_url, custom_alias, expires_at, is_active, created_at
`

type CreateLinkParams struct {
	UserID      uuid.UUID
	Code        string
	OriginalUrl string
	CustomAlias *string
	ExpiresAt   *time.Time
	IsActive    bool
	CreatedAt   time.Time
}

type CreateLinkRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Code        string
	OriginalUrl string
	CustomAlias *string
	ExpiresAt   *time.Time
	IsActive    bool
	CreatedAt   time.Time
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (CreateLinkRow, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.UserID,
		arg.Code,
		arg.OriginalUrl,
		arg.CustomAlias,
		arg.ExpiresAt,
		arg.IsActive,
		arg.CreatedAt,
	)
	var i CreateLinkRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.OriginalUrl,
		&i.CustomAlias,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const findAllByUserID = `-- name: FindAllByUserID :many

SELECT id, code, original_url, user_id, custom_alias, expires_at, is_active, created_at FROM link 
WHERE user_id = $1 AND is_active = true 
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type FindAllByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) FindAllByUserID(ctx context.Context, arg FindAllByUserIDParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, findAllByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.OriginalUrl,
			&i.UserID,
			&i.CustomAlias,
			&i.ExpiresAt,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findByCodeAndUserID = `-- name: FindByCodeAndUserID :one

SELECT id, code, original_url, user_id, custom_alias, expires_at, is_active, created_at FROM link 
WHERE code = $1 AND user_id = $2 AND is_active = true
LIMIT 1
`

type FindByCodeAndUserIDParams struct {
	Code   string
	UserID uuid.UUID
}

func (q *Queries) FindByCodeAndUserID(ctx context.Context, arg FindByCodeAndUserIDParams) (Link, error) {
	row := q.db.QueryRow(ctx, findByCodeAndUserID, arg.Code, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OriginalUrl,
		&i.UserID,
		&i.CustomAlias,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateLink = `-- name: UpdateLink :execrows

UPDATE link
SET 
    code = $2,
    original_url = $3,
    custom_alias = $4,
    expires_at = $5,
    is_active = $6
WHERE id = $1
`

type UpdateLinkParams struct {
	ID          uuid.UUID
	Code        string
	OriginalUrl string
	CustomAlias *string
	ExpiresAt   *time.Time
	IsActive    bool
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLink,
		arg.ID,
		arg.Code,
		arg.OriginalUrl,
		arg.CustomAlias,
		arg.ExpiresAt,
		arg.IsActive,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
