---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shortener-secret
  namespace: url-shortener
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA3r3zSKwmG1l7pwJtiR/zliTcwJl7L2z3WSgBx0QBrmHQc1esHeAm1o7Lr6BhTF9jHxTI+xxswPLmAz9KZu3j+Lb3bUW4slHeQWRMNn2zKJ6KGImQD4dPacnqtpffm+5x96qfoaaB5gAviyyXsgShqjYNlpC+PSRDAuCKtKTz0HQSgZ+HOHKqXnvwY5VYS7j6vaPcX32IXid4O1T/7KW2AbENzf8E2x/XjRZGyU4a/1rS4RBX9L0bb9RJ22W5qw2F+GZaiHd8nwpwFed7LVaNjh8Rn69Xl2//AJCgP0NV51OkcDP7SqSsAwHFczZvAgAz/OMGcwNLRkHb3od3G5IQ4PTSMoQ+QfzZUto8UYNvUh/vJli//OQSXwYMuR3zn0/2NTlX3oDArW1/e2s2ebw0EMZ3RrhDzyjt5szr0MYUKCZFmbvDNr1FzHE8uHQVGutDKtN4ObvixE5Rkz8EGuYwOweVA7OIBxsAq8261gpfkcOWUTQPVYfsnvrh0/ITP0bJnwHfgMxuM/RWvuuSQK+cVZ5CSj3Q0PU/uUZBQrqMdizvfg6c3fMnMnnj0inyXW88CARE1/kWZBPGEvqHLI5MDNshGtiiedX2UzDpvfW7rRmkPNI20XrEVCtYIeuepSQGhnDOXg30T5Q8bXv3dlErZ2x+V8X87yvxW6qQZ1miB2dOXS/16/HCz7qSYVjehtfQRprE6DcsV
  template:
    metadata:
      labels:
        app: shortener
        app.kubernetes.io/name: shortener
        app.kubernetes.io/part-of: url-shortener
      name: shortener-secret
      namespace: url-shortener
    type: Opaque
