apiVersion: v1
kind: Service
metadata:
  name: shortener
  namespace: url-shortener
  labels:
    app: shortener
    app.kubernetes.io/name: shortener
    app.kubernetes.io/part-of: url-shortener
spec:
  type: ClusterIP
  selector:
    app: shortener
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
 