---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: url-shortener
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    app-password: AgBQXGNDiAs1ebGv30m18oqr7WZw8WqkKkZFDVmt0gbSK6C2l0SsfWkFA0FllnW3emT6T6WvPdcBYJVjB/xbfA6amofoe5oAshtaZazTxpPXUUYv7mpdKE05C9rayrpmUSlF/Na9HBJNMXI62XkBcG3A/NMkybB3zbd21dEmtz4xdsMarB77J6qZoEjJOhoVuG+axkMG/TTPqV62k6GlZytuh9bKhcp+sD13bcKNFeCUC9Gd1sfWM6e2wJAj4DRoyInUlpGJhSSoVo6aYGQBASBl2ZSov71aMXRFMSI20TyQ8ODlwElRk33qldlSA+p+09KDWUJQ4OePxYTFOafZzkCgYtMIvpoBK8JVnF00JlyDZSQKCBbBNMABXBkpwtXAHM92XnasFtbZK8LUXtEIY9rfVFWxgXs9wzw2dm5+aFoIRMy+88aYI8e3XqI0KP7KDeQU4jGn+aGI0eYMIYvN6slClQ3OScDoGBD6FQgVVe3VGpShEoZAVdCJJuJ2OP7+KeWLSxU8TgU6tC17Dy4L+9wAijzkE9newb4yufCTh00qBSfo72Wvmn3Hx6aCuuI8Mr7BCsI9G9NoT4gCjOGTTlHvYpSy/hcY6pipMzD4+B/HVBB7biwP0vhVGSipGeqvuf3sH+KYBXkFgiqvQeEnoCAmFbriULA3X43iS80I2pkr8XsSnixY5+7nMsrRfao9KX2QpP2lGL0=
    password: AgCBlSDykEQxinJR9wkpjMQekX7v0Vr35T3sXYiDhT/Y+4S1bXLFGejjkYOzbXnbAZb5rFiZ18q3ptJ+KOZbhYbQlIWp+pRzlnPBZN1NqganU1zQf2KJ43i1XxZNVVu+sTFki+pZGdfsFx0JQ1egBiwKvibdAUV4tCQ9bzTWDydX4E2Mk6l5eJ5KtzOYvG2xtwQobxsYbLmGGlkcNmoyVWn/+FfOip6z/8U5ZTO1TdwPOS3Jgp2MMMnnWHifzeFMTEd3l0IA4YoEch71HsBk4glEFn7eJkC7F6DJvb5YAZKxVLDOu44K1vclO9s57IgMh4p1OhyuIdK28wY9JAVuF6oFBnesiyJdYBWldjX2KxO2gXX78hhj21Wm/v2sERVOjutkOcBzAjdTuuZWiTzr5hSkWd/Y0dDj0q6U1WLA/H4CGdkbPDX9YtWtx/eR03r3GIKXhoOBNS/m8ef0hRHCJBljNppDVYj1cBbCyNUq0zDPkAzieLaPySvmDq1bMUYOhYhAzJShE4A0yv0OYVQoEnEdAP6zWCvD+NcYervH6XYF/fBu4xdUK6NdlfXL2mippple9i3DAVold+zl1xoqVo58nCNSosZVWz68sVWXzNLKv8VHhBS/VzidGtUdNjZ4hpEpiDb3I8XSlAr0ZvPuZO/jYpg86yYRTvmVMLao/RjIEtgPBhsd8axn8sR6PCeEFrMjbHjDnss=
  template:
    metadata:
      name: redis-secret
      namespace: url-shortener
    type: Opaque
