prometheus:
  prometheusSpec:
    retention: 15d
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard # "standard" for minikube, "pd-standard" for GCP
          resources:
            requests:
              storage: 20Gi
    additionalServiceMonitors:
      - name: gateway-monitor
        namespace: url-shortener
        selector:
          matchLabels:
            app: gateway
        endpoints:
          - port: http
            path: /metrics
            interval: 15s
      - name: shortener-monitor
        namespace: url-shortener
        selector:
          matchLabels:
            app: shortener
        endpoints:
          - port: http
            path: /metrics
            interval: 15s
      - name: redirect-monitor
        namespace: url-shortener
        selector:
          matchLabels:
            app: redirect
        endpoints:
          - port: http
            path: /metrics
            interval: 15s
      - name: analytics-monitor
        namespace: url-shortener
        selector:
          matchLabels:
            app: analytics
        endpoints:
          - port: http
            path: /metrics
            interval: 15s

grafana:
  enabled: true
  adminPassword: password
  persistence:
    enabled: true
    size: 5Gi
  service:
    type: LoadBalancer
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 5
    periodSeconds: 15
    failureThreshold: 10

alertmanager:
  enabled: false

# # Enable needed addons
# minikube addons enable storage-provisioner
# minikube addons enable metrics-server

# # Access Grafana without LoadBalancer
# kubectl port-forward svc/monitoring-grafana 3000:80 -n monitoring

# https://claude.ai/chat/42f06ad6-ff7f-40c5-8633-b0c8df8f9859