services:
  kafka:
    image: bitnami/kafka:3.9.0
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - kafka_data:/bitnami/kafka
      - ./infra/kafka/init-topics.sh:/init-topics.sh
    networks:
      - url-shortener-net
    restart: unless-stopped
    environment:
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
    healthcheck:
      test: ["CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s
    profiles:
      - all
      - infra
      - messaging

  kafka-init:
    image: bitnami/kafka:latest
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./infra/kafka/init-topics.sh:/init-topics.sh
    networks:
      - url-shortener-net
    entrypoint: ["/bin/bash", "/init-topics.sh"]
    restart: "no"
    profiles:
      - all
      - infra
      - messaging

volumes:
  kafka_data:

networks:
  url-shortener-net:
    external: true
    driver: bridge