services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: postgres
    restart: unless-stopped
    healthcheck:
      interval: 10s

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["mongosh"]
      interval: 10s

  redis:
    image: redis:8.6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command:
      - ""
    environment:
      REDISCLI_USER: ${REDIS_USER}
      REDISCLI_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
    
volumes:
  postgres_data:
  mongo_data:
  redis_data:

networks:
  url-shortener-net:
    driver: backend