# x-common-env: &common-env
#   CONFIG_SERVER: config-server
#   CONFIG_SERVER_PORT: ${CONFIG_SERVER_PORT}
#   DISCOVERY_SERVER: discovery-server
#   DISCOVERY_SERVER_PORT: ${DISCOVERY_SERVER_PORT}

# x-common-healthcheck: &common-healthcheck
#   interval: 10s
#   timeout: 5s
#   retries: 10
#   start_period: 90s

# x-database-healthcheck: &database-healthcheck
#   interval: 10s
#   timeout: 5s
#   retries: 10
#   start_period: 60s

# x-common-service: &common-service
#   networks:
#     ecommerce-net:
#   restart: unless-stopped
#   stdin_open: true
#   tty: true

services:
  gateway:
    image: aziz-dev/gateway
    ports:
      - "8080:8080"
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - url-shortener-net
    environment:
      APP_ENV: docker
      SERVICE_NAME: gateway
      SERVICE_PORT: 8080
      SHORTENER_SERVICE_URL: http://shortener:8081
      REDIRECT_SERVICE_URL: http://redirect:8082
      ANALYTICS_SERVICE_URL: http://analytics:8083
      POSTGRES_HOST: postgres
      POSTGRES_USER: aziz
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: gateway
      REDIS_ADDR: redis:6379
      REDIS_USER: app
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_EXPIRY: ${JWT_ACCESS_EXPIRY}
      JWT_REFRESH_EXPIRY: ${JWT_REFRESH_EXPIRY}
    profiles:
      - all
      - service
  
  shortener:
    image: aziz-dev/shortener
    ports:
      - "8081:8081"
    build:
      context: ./shortener
      dockerfile: Dockerfile
      # tag: aziz-dev/shortener
    restart: unless-stopped
    networks:
      - url-shortener-net
    environment:
      APP_ENV: docker
      SERVICE_NAME: shortener
      SERVICE_PORT: 8081
      POSTGRES_HOST: postgres
      POSTGRES_USER: aziz
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: shortener
      KAFKA_BROKERS: kafka:9092
      KAFKA_CONSUMER_TOPICS: "url-shortener.urls.created,url-shortener.urls.deleted,url-shortener.redirects.requested,url-shortener.redirects.resolved,url-shortener.redirects.failed"
      KAFKA_PRODUCER_TOPIC: "url-shortener.analytics.aggregated"
      KAFKA_GROUP_ID: shortener-service
    profiles:
      - all
      - service

  redirect:
    image: aziz-dev/redirect
    ports:
      - "8082:8082"
    build:
      context: ./redirect
      dockerfile: Dockerfile
      # tag: aziz-dev/redirect
    restart: unless-stopped
    networks:
      - url-shortener-net
    environment:
      APP_ENV: docker
      SERVICE_NAME: redirect
      SERVICE_PORT: 8082
      POSTGRES_HOST: postgres
      POSTGRES_USER: aziz
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: shortener
      REDIS_ADDR: redis:6379
      REDIS_USER: app
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      KAFKA_BROKERS: kafka:9092
      KAFKA_CONSUMER_TOPICS: "url-shortener.urls.created,url-shortener.urls.deleted,url-shortener.redirects.requested,url-shortener.redirects.resolved,url-shortener.redirects.failed"
      KAFKA_PRODUCER_TOPIC: "url-shortener.analytics.aggregated"
      KAFKA_GROUP_ID: redirect-service
    profiles:
      - all
      - service

  analytics:
    image: aziz-dev/analytics
    ports:
      - "8083:8083"
    build:
      context: ./analytics
      dockerfile: Dockerfile
      # tag: aziz-dev/analytics
    restart: unless-stopped
    networks:
      - url-shortener-net
    environment:
      APP_ENV: docker
      SERVICE_NAME: analytics
      SERVICE_PORT: 8083
      POSTGRES_HOST: postgres
      POSTGRES_USER: aziz
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: analytics
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017
      KAFKA_BROKERS: kafka:9092
      KAFKA_CONSUMER_TOPICS: "url-shortener.urls.created,url-shortener.urls.deleted,url-shortener.redirects.requested,url-shortener.redirects.resolved,url-shortener.redirects.failed"
      KAFKA_PRODUCER_TOPIC: "url-shortener.analytics.aggregated"
      KAFKA_GROUP_ID: analytics-service
    profiles:
      - all
      - service
      
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: postgres
    restart: unless-stopped
    networks:
      - url-shortener-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 10
    profiles:
      - all
      - database
    
  mongo:
    image: mongo:8.0.21
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: unless-stopped
    networks:
      - url-shortener-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 10
    profiles:
      - all
      - database

  redis:
    image: redis:8.6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./infra/redis/redis.cfg:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    environment:
      REDISCLI_USER: ${REDIS_USER}
      REDISCLI_PASSWORD: ${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - url-shortener-net
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 10
    profiles:
      - all
      - database
    
volumes:
  postgres_data:
  mongo_data:
  redis_data:

networks:
  url-shortener-net:
    external: true
    driver: bridge