apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: url-shortener-frontend-config
  namespace: url-shortener
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT # Emits a clean HTTP 301