{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mongo-secret",
    "namespace": "url-shortener"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mongo-secret",
        "namespace": "url-shortener"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "mongodb-metrics-password": "AgB1eBOQ50FWwLJ1K3URv1hp/YUH59UutWvfzNg4NIOxIQrtkN0le+8LNicfVPce2bTllLmCjsw9Q9qtEv82UnvzwnUfNICpPcucUpuzq/a53vycwYxydTip8yUf3ae7+o1EQneB4ds8kJlncM/O/bzgaK/UdvkVmGWeRBbsiytWiih4aojSfZ90wuD5vTHBNQPWAjfO5xh3c+kuM7em9dSrqZSkF938WOy+i1vsCMJ55ESBQAW0mvhWcZ26TZ353PIssHmKmGHv+5A5E3kPK0f/wypi2FOzauKJusYrtDYGdkt08Ix7ru1ViRXPTJgm3LJm+jEWQQG+2TVnljWWS64xuCjI8J8Nb66hcW/939YtG7NbxcHhN40EiFXY1QVWcml22BQ2/oK8iPlIfpZg8qCA+5vBJ+ULZR3eMqe7mm5VgQYJi3OM986L/9livpJYcpE2RU7EEK27SpGY9aN/N1SHoP4zvpC6pAe25ThHvRsX5kUk3hPClqj0TrhMZx64QSOQLIVIRDr0BYghh4zfOCvapMimo5p+zqV/hhoP8Sw/i6uSZCChzI6kYjcXVo6NL6s8N2xYd8wiFdlkn8CcPYijoCT89NLZY9i64ZeEbEJD3EiNfT9TtLPrJ3dzLZCXYshpQ671Hiwdtf/JmpTp/Rs6SRPAo8ds6+2D7VqbQemt1ZJXADbAbFjiHVkrNXhfwGQgYmpVQA==",
      "mongodb-root-password": "AgAFi+gK53YL2pt29nND3ukfAbehL9jiIs0ItjIOMZBWps/MZkT0jDmZwPu5XlxINWuj6/upIp9RfAL10XrzGDIbikTWuZy48xY2ONyql1YunGFUTiAyRFHxjKaYiIiMYLbMCskM9JM3nzMMcYTYFjf6v/JV++Qp0jdmZ+EtpVahRPB/1nLLONj6S/RFcN1l7Iv5DktaGzAXD7r+ak7J9qqwj9ac3Be5KjKSgatuLZq+HrAwuvV19XpL164DMOXcrNPTaKgQeN8TRR1HxdnFBQYt3ngc8+xHUmQMmxxZbyULano6EPuZvh5Y/QTa35X8TI6/FK0RimY6vsVdo0oCaYH09wqzFudFwz0b0A8LCanwfq8MSNuXCutwCJUtEXA3JHxj9wLiS57UAh4L++hSMCsb4/gOxu19veAciDIWlBL6tLoOOdS9tVp3SX3Qhld4Y3jOZkYgHUBfnJm/etAmO1PZ8Xz9FwQpltfpc7tksYp03XvhWKP1lQli1ET1M5JkIbaFo62zLUPrVRDRaFOx7vYvj+fk3yUn+nA6R0BZCUXrOS+mQtgMo+ELHIiUJipq6iCik/6HPVXytfTsQC4gLQ2zSiVSk8aBfbAWMXZb6VHVYEpBlZx4WdvaCUMztHvj09mB62+4yxBfCR+4g8j7nBf0cb6SJkmt615SEw2HK8+VoRy1lQ2F5dXsWSfsHxwXG7/6ZSGdyQ=="
    }
  }
}
