{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mongo-secret",
    "namespace": "url-shortener",
    "annotations": {
      "argocd.argoproj.io/sync-wave": "-1"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mongo-secret",
        "namespace": "url-shortener"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "root-password": "AgBhQGa869hCrqBoUrvkIWlh+FZqJmnaYsWkowalAsUK7PDYBV6H4eICf0P9r+cNCwe/l9PeTjn8eHv0RGNlgidS/mw3vsJOeUhWbN5ypEVyYcYj1NGXFSDGoXqulVtL9Fhogzk5mJ1jGEysrMWHufi895x+ITHJ1jqSrpU3ukxri77iqvZOzwD9mkr4jFK15IObqdG5q81Wux/htlCM6Tw2QzeNdx7IrfKTm9NFaEArP7kPwlp5Z/ByUr+Qc2WeDrInvnXfPBNLKHCYVanGjtPXMHv4IiBfvceGU3nShUzsqYVET8LsQm5WwEVQWrWa+fBwz5kHIA43+OvLIcmgH316jJ3R9oiov5DrXRKE70siubQ5UxQwLfvZu6bq20mDjUACmm3qDZvm5HPU2TAe/I7Iqif/CeXIdqkFjPiXl6Fe9RQ+TEhyLZZ0RrrfbfDriU2Gd06v5kcZOQ4HVKr3Flv3/wHn3G1rn+V8OnhuZeTXV7rEAOH4oE4r14FsdHqwxvq3m4zbekGdAygdgGIoxM+2IImQmfJZU+OHfS835nrnIK0xNYbM9vJ/emxG29LDq53DvnK6Kk2TcyirQgIEwVMqXlbVU5UmJ/LkN0+n3IB8Ed9QHLkb3RezQlhGqmGfJfRLYyc9WnUPvdWgcd6TysXEcfoFSkyrZAHhWp1cqMEY1OAjE8MtzWzNROCrZ9LEWzTVt9KOxA=="
    }
  }
}
