services:
  gateway:
    image: abdelaziz333/gateway:${APP_VERSION}
    ports:
      - "8080:8080"
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - url-shortener-net
    environment:
      APP_ENV: docker
      SERVICE_NAME: gateway
      SERVICE_PORT: 8080
      SHORTENER_SERVICE_URL: shortener:50051
      REDIRECT_SERVICE_URL: redirect:50052
      POSTGRES_HOST: postgres
      POSTGRES_USER: aziz
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: gateway
      REDIS_ADDR: redis:6379
      REDIS_USER: app
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_EXPIRY: ${JWT_ACCESS_EXPIRY}
      JWT_REFRESH_EXPIRY: ${JWT_REFRESH_EXPIRY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    profiles:
      - all
      - app
  
  shortener:
    image: abdelaziz333/shortener:${APP_VERSION}
    ports:
      - "8081:8081"
      - "50051:50051"
    build:
      context: ./shortener
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - url-shortener-net
    environment:
      APP_ENV: docker
      SERVICE_NAME: shortener
      SERVICE_PORT: 8081
      GRPC_PORT: 50051
      POSTGRES_HOST: postgres
      POSTGRES_USER: aziz
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: shortener
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - all
      - app

  redirect:
    image: abdelaziz333/redirect:${APP_VERSION}
    ports:
      - "8082:8082"
      - "50052:50052"
    build:
      context: ./redirect
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - url-shortener-net
    environment:
      APP_ENV: docker
      SERVICE_NAME: redirect
      SERVICE_PORT: 8082
      GRPC_PORT: 50052
      POSTGRES_HOST: postgres
      POSTGRES_USER: aziz
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: shortener
      REDIS_ADDR: redis:6379
      REDIS_USER: app
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    profiles:
      - all
      - app
      
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: postgres
    restart: unless-stopped
    networks:
      - url-shortener-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 10
    profiles:
      - all
      - database

  redis:
    image: redis:8.6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./infra/redis/redis.cfg:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    environment:
      REDISCLI_USER: ${REDIS_USER}
      REDISCLI_PASSWORD: ${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - url-shortener-net
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 10
    profiles:
      - all
      - database
    
volumes:
  postgres_data:
  redis_data:

networks:
  url-shortener-net:
    external: true
    driver: bridge
