apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: redirect
  namespace: url-shortener
  labels:
    app: redirect
    app.kubernetes.io/name: redirect
    app.kubernetes.io/part-of: url-shortener
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redirect
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80