ALTER TABLE users
    ALTER COLUMN created_at TYPE TIMESTAMPTZ,
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,

    ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
    ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;