---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redirect-secret
  namespace: url-shortener
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCpEtUrx3yoniERdBZBfMzODPVzvM6/UzgE/1djAE2bmmcUXznheoARw4zSRjj+pCr1RzUatPjv2x/I9NBgsB5icbIxF6gRIrGFVXCJukBLv/s8GKzJPStj4YIPsLtmqVcaOyYeoOmAnVysl51OI5h/17dZ4vjvPNlwYPy98LPfQs5Kb11fwW25OUBePNXTZtfO/ovKho1qtxRos9jVKqo8joRJ83ZJmb7Fh1OrwOazdHZtvtk79Zj/GUoy6VGdYbvxqLRdMjYzBO/tYZ1jFXSxuHqCV0YCn5WMu/L98VnitNJB4D/QGVVEaHBtVvS6zrWTMbFv0M1bDXVUQaaqfIAG9xhSn3ECcPpzlFdNDs83xI716MnHZC/71GNXA54SD5xT5tl2hQMQysCDi+7Rv2ebEnfJss8M/RZf6C+Sq/wCz7OPqcwr+VMCDmQB+Gydgl2Qmgwgnbu0M5ADZGd0TZps/qqdbq739b3KU3JJ4M+ydjp8hOLpJ+xfRkelPxzCAla6FEEIf2/9EM4XKx5coVRo/GFB9JLAldDoJxONDy+AbUxE35EJY2I5FQTEQI970wzSQd267BzhKMzVRkL5mTpA0JpNowNe0zhJUxOy1RBvxbPypJzH0nxbj2utg66celbzIMaopCSUJKOc7Vw+B0NGDrMHOezHXEmF4u2ihlEWXUwIrgGUiJEHbr+EtgRjLk3CK1AT5Y7y
    REDIS_PASSWORD: AgCFBX46Cgn6My2ED6aV2ibtfagIJaHA1ZCN+7aIkgv6ys+EMsgH5RNwFlN8FVH1RDQaMQwQ6CMFmb+GKdRW1+doxOy2nt8R+zTxImx7Rof/3kdNgK5UXfUITmgB4ylL6KhX/DhOk8Y7mIQa5BotaIm5g8sjYWRORm7p2VyPICkzLmFYprQ9VZxL/81JT9pRWsmMiK167VLy6l5swGvEn9RtL0kml78x0/qrkj+IuIQVWgxWsq6lMFq4qniejqMF/93PEmbv0GCXAHRdlXBzz0u3haBWfz4w2kkXEBeu3HmPQiU8NyPh5MgHko+3CrFFp6XnPrgvRvYTiCb+VLFG2DFYlIwQ9TqHG05ereSsOXF0RavFqyCyMq5s1efB9NETHYmjUHPKg6kJQL5saelN0FYQNWI0ESGFhoVss5EqpHhxA1LAYhZp1JgUYFM7Hz8cOnMR9lFrlaJ6uM+9Jic3ueLUvrG73Jx0HjpWEcxydIeRbXAMVUI/t/Lb//qgQwC6vPDDPK32vCQV/RHSGVu6sxSMT+9vtyuDnLufRmTduuODLyLqwHk6bqNtI9V3cW71wS1UtsMFpRWAXBjOcbh35gjVQK4M8re0VyIuaGBRYRcJyHH0jxUjVO5Bsqj7sQoR3Pm29fGryVpwtvgfL92GdTIAYwMwFO1Byp2DBJXwu0lG36j/vdUBQ7miJt0RVRGLnBiTM9vhDXc=
  template:
    metadata:
      labels:
        app: redirect
        app.kubernetes.io/name: redirect
        app.kubernetes.io/part-of: url-shortener
      name: redirect-secret
      namespace: url-shortener
    type: Opaque
