{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "postgres-secret",
    "namespace": "url-shortener",
    "annotations": {
      "argocd.argoproj.io/sync-wave": "-1"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "postgres-secret",
        "namespace": "url-shortener"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "password": "AgBntTY9V3naEBmgn1rE80qAnCz2EhVlxeDHVoJzn2MZrsHPt6qU/m98Zl9KVb9c5W3gONSsB6KZq5kCrDaQlFuBzvbDkNyTT3a/Zt6Iq22XYC3+ONFm6hXDio95YV3n4w1JLHQ0LZwNc3KWyfOPpXfVs6+o1e1UcUQ4MaGzYJlo2+nSiT7Vh0xz+6sk0D1YfMA6+81l5KcpR5eeZjSfcwYO67jYw5YBb0eW+GCsPI9sYWbEHo+lKLiL7+nqvlwCzB+v6Z94VNRlNdXpbN1zYE00/8QoO3M8Rfoei6gf1ycqsI+OyV1sTtU8a5IEsnbFhQWH3C50t+KodHidwgXoor6x+56WMuR0RXq799M/Rdpo1n9MvMs9okpuRyVzGEy52HxK7uKAqqPbdDbegKbyQoONUQ+cuPVYh1gI/m8Tvuu4dkm0EO9csSjT9lrB2DndmrBsi0v+UTyfer25QNL0cUoArOm6eai2UUXlZTrFxCxMHHEEV7aLPNY5zR0ZFC0jvo8Qp5/b/7kgGsLI/qFNVp6zB+MiryPfLg8hyDFRs+rM7aqY6kS5E1Drl7NcedgNahgBBUa+gu+xfMjkubwKgY0j/FXGegtvoOxuE2RKimxKDtNrreQ/uzcTmVOqi7Dg3CauN1sXeeogugFv+fBNEycPwICq4CwhwMBFnzH22GOncaQ1xCtBtJIfPphRQCK+oZb2DoJwNRX+",
      "postgres-password": "AgBXYijvdUm/l3K/5MZhkOYKVXBZwtNmi+ni72MhvNbm+2v9zPO1RTIC1RfIxaAQsxj6T9ILtXMSkgC9/HDr0y9tK0tqaxhF4IMFuYFEAP8HTdsh0mmO8equMejvDrogEBEZAv5V4xbPghViWCun7hcmfVjIhY5P/JBLd4MLAHiM8ZU+0oRdAnVfDIf4UkKNG+8Dz2WrheN0lUXBXeeLnhZ6vcMyvSygD8mRl1fgnQQhgPOxaZnZo7KnGRoz3FT+0wYkg0JGt+wxVHBMLyM3fXpkUhPX/7KDXJGYsS717eALgYUlQhiOiEyV/c4bB5lQxATSBE7EgZm9Z+2VbhPnobASKzlLz4Ct3TeayWxVnkovMIbx53DtisigdRC1pFlrN1PBmr3TUI+fg0X8lsmbun83tzv/qC3x+vTRv9VItsoXuskub+PT4d7PcS4ir/0XlggaCcHdVqF50zx89DFItbtWplcF3bwvWa9TaYH9pzwnTVhhwrzcOEnfgOOuSsvJBaJgwJLBy/7ttOkKxHyU6UPAUR5EnoUKhAoCJyUJpPgM3YiS0ni5N9HPF3cCv5dKJz284U9IrybIS4Ylc0uAjrzM8CtrGhuiO891kIxDOoi4XD2vBXWM+TauK47PAKcGzKoc9nzOVFNlE4tY0X11o/3w2Yg02r0ytk1ccpmo3Vet/u4qGFSRPLVmgfnRhvC+0uqFSOmfmC19"
    }
  }
}
