---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: analytics-secret
  namespace: url-shortener
spec:
  encryptedData:
    MONGO_URI: AgBYj/ULrAKohcrQhZyrhDOP0NcFMZO2HdgtvY3t8tuFANBItEVDvkuxCvJ7lXpnt6oegC9mHRjRSAb4+g+BhLf0k9UjHlcSapjHWOj9wz9VoO8Ig2xkWaUdEWWtP+hgO9Ts71KavNFeGow92Av7qpTNRb3l80lgoHMrgeRZPvQ8ev2FtnLv2YzFT7eKUrXb1UfI8K5z5ZD/4YmOPOdIZUTOrS+WXMjwY2K0nePip4+5g+Xj4Y1YVg3R9BDX7X1/1U7ACeAp1UCg4PfUgSpVOtaHhLzDTw5IOUqn4X4tDT5bQl31Hur7/PlcVbG+rlXdj+KZKAbLPcSJ3AAsNjzvucPi+MIYktU8aCsPOay0Y68JtVrO1+JPctqdyjubLhGfY+urmPfekUfqUqkiZ7GbJHk+FZWBucBgpgemCYTCcbPHtj8p7AMXsbVOeScthPgqO4sNGo5/6R1scT7dYJVArF0j/AITyB5aPgptkGk0yFMAM1JmNlwso+HRiA0Ja2MMtJRdaE6h6HT0YgRVsZslJNldBITSkkXU4WFkJO45M4GQcllbdSe+LzYiWXirbhef3yyHU+UNRaLrn2aVRVO25g/XL4KN9blVWwB56YhkDE3x/tz71TM4lM9NYzB6YreNV/08J8CtH19tMKL33p3KKol+dFnGjaTgw3n6PKdH6YTgHFxPQ9Ck/q4XUoowdsSEeVQpaW/j0jX06hnZicRjVbEBH8s2FhxFYcxaDgg+WZUusMMdUrY0XRJj2aQJKTi2NXI=
    POSTGRES_PASSWORD: AgCAOIn+r4ED/N4BuM+2WK3qUsGS4VPaVQpRnCNRxlV+aj4T0dDS/bKgLHCwWku9pAiiX4j8tpygoulVWcRXJY5uAFgtV4u1miP57QHc14hkGEFin6SnOEaLjObaYJSbJS7fDLQL4spathfv/6EoWwyX6bSaqe3rcxxwbykrJxuWJ3IXtyW2g3Hx99dL8pdvir7L+jYoT+ztnTmrl0AniDwGwCVWfWJgui9e5Lq8xdveHHstfzb9ym1y4vmtsG+t5x26OeWIvIby32lHNsd6X6kKk9k0qhiJUMzNiG/GiRm5JZIBsmGscrn7yj/nrz9w7kmYnaPGIRxl4QHQg+ap0fEO/Q+isRhtM4tbtvYqz09wof/vA2KLBK0fcvyF1YKcdi1nxTuZcG2T8IWbN9vEVFSaryNi8ONtwKMbfQniVRocVrM9PQ4WgnVoVPr4vhAg63x5giChu+eo3j3loONgTpOX/TQHkOZOaCudF4BqNHdvSlb8sK8BOw8x1dPfo3rv26h11BN8vOqyje/UcYSc5KdKoC0jUQrjW5zUBiMAcarkfhWxf+cwhSngL+A56wqLsYt5VqdbTqjg5ey3jW5RPNlUN6vW1q/xFywHrLGlpAm+ScIT50MkYg50t17r5SBUw5N57yey4FVbZbNPoyEHfUXIP9YJ2SpEPaXizPMj8JxYPLjjPKrN0DPc8cbZJDUc83ZIy5xaiDrA
  template:
    metadata:
      labels:
        app: analytics
        app.kubernetes.io/name: analytics
        app.kubernetes.io/part-of: url-shortener
      name: analytics-secret
      namespace: url-shortener
    type: Opaque
