{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "redis-secret",
    "namespace": "url-shortener",
    "annotations": {
      "argocd.argoproj.io/sync-wave": "-1"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "redis-secret",
        "namespace": "url-shortener"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "app-password": "AgAo00hTmgEc3afhDxNxewk49EsVNA0n9YRcDzA/t0hHriyL2oIbZZDf9fbS+A7JCY8c4hpLFxYfZBpjbQith0RqeInjWV3FYEy9D1OGW1dpuDskDcUzrdcwaJLbhYc3LVXaPoQtZXwUP3iJIU5LuzSbNAtFNwf+Pm4ERbUpxpYtIIeYG11+g9IgTWzq9hrMrGLOsqkrGPY+9jXKGFd1X6v8VCQTPM3FemZMWFBtfWRBr1XOxHPA08/oQeZmHmpafeHkeZOVz86OAUCFbapx4otniT0vVZhnP4HLvY12k5JvPUU072w0BYTaTKUJKTZkEsUnx9wq/P+UCcroD+pxJF0OJLNWqeNGOllEj90KbtUC6LWcVZEP8Ei6vHh7x+dZKXDRzVUPzVp2cHflD1voaNFBhFpzfKwBw5Ywv+FfT4JS1RDNeHZolEPOdLXOj8isgoorlZrFSOL4o33i5cP9Gilf9B5IlBQWrLNdA+5HAKw8EF+FKhRXtYFv77G/Y3Fpj/p0J1j0DO+1+lCSRBXlk+f9btAskxR49eTMttanFBNdXVOFGG26jw6n5vh42KyNlwVWTs5iju3KvexZc6mg9Ds0bCS3M9ny2Il9qKUsvbUyunfmQsMfqfOX9o9I+ITfp8Bs6J8B1K4EqMG9Ot2WHl6LIlRvCY5mk9oXHAQSV3sz7dPkQBjhIRvfXuz71v2sXIqy0jY2PNc=",
      "password": "AgBOdNX/tUMHoZQZ2FnNbUgW/AInG5lALTIy66Xb5KmdZYch8mjKQOB6cPMNxfbwNAh6KeMXtTnlLz3+k4BcmQGcgagv36JHht97YapuN2yJzkA+UtS6GuGyN0Mv84KyM05/AGpJ6N0WsBCMHgoCOM+z6sAPkwOwGjPQIjbImBH/ITbeg/NXjxec36nRbEhr/4pJzP6vupVih06cJg2xJKEu0y5bsPICKuOdvPY999fi4gLEN2rfIU8al3eZER6RuduDSp+Ql+kVwaKHtA1oL9KSM2C6ri6uMoeV+DSnPAV68+1cOPn4U1tFutHxW0jerTtOTDHOcUcK9yEXwoJ3Zc5OfFIBaEsM3Wh0wsEIqILSAsnxFO3GkRWUPcOZ20tJkRgWHHPEeEJsMkVGORfBudK33h3qQUkVjbjnOg/CLVD/r8/52t+o8FeOvEC3J04vNsDjAcr8pg1h10H7h9Hi8pK3iqlo8oivVOwwEBDypIxGdxhnyM99q0uacWNOuFPiHT1DrEsphVstFBwDFabhFzHsGji62VAF/bm99m+7XMy0KBoCNCqz25GDURkFv6LGGnghwqKFZX7Lr/f4ATyTIQ3ufskjxBCvdaqHuyGZEGeCQE4eOC4zJ2mllBJpdj38LU+/vOTJxJzS87gQMvDj9fG/XLjTantRvpphMAHngLHLJeH8Mb6W91nz4bojtRk95Zbz5AHgICU="
    }
  }
}
