// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: redirect.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCodeRequest) Reset() {
	*x = ResolveCodeRequest{}
	mi := &file_redirect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCodeRequest) ProtoMessage() {}

func (x *ResolveCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCodeRequest.ProtoReflect.Descriptor instead.
func (*ResolveCodeRequest) Descriptor() ([]byte, []int) {
	return file_redirect_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ResolveCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCodeResponse) Reset() {
	*x = ResolveCodeResponse{}
	mi := &file_redirect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCodeResponse) ProtoMessage() {}

func (x *ResolveCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCodeResponse.ProtoReflect.Descriptor instead.
func (*ResolveCodeResponse) Descriptor() ([]byte, []int) {
	return file_redirect_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResolveCodeResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

var File_redirect_proto protoreflect.FileDescriptor

const file_redirect_proto_rawDesc = "" +
	"\n" +
	"\x0eredirect.proto\x12\bredirect\"(\n" +
	"\x12ResolveCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"L\n" +
	"\x13ResolveCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl2]\n" +
	"\x0fRedirectService\x12J\n" +
	"\vResolveCode\x12\x1c.redirect.ResolveCodeRequest\x1a\x1d.redirect.ResolveCodeResponseB\x1fZ\x1daziz.dev/redirect/internal/pbb\x06proto3"

var (
	file_redirect_proto_rawDescOnce sync.Once
	file_redirect_proto_rawDescData []byte
)

func file_redirect_proto_rawDescGZIP() []byte {
	file_redirect_proto_rawDescOnce.Do(func() {
		file_redirect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redirect_proto_rawDesc), len(file_redirect_proto_rawDesc)))
	})
	return file_redirect_proto_rawDescData
}

var file_redirect_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_redirect_proto_goTypes = []any{
	(*ResolveCodeRequest)(nil),  // 0: redirect.ResolveCodeRequest
	(*ResolveCodeResponse)(nil), // 1: redirect.ResolveCodeResponse
}
var file_redirect_proto_depIdxs = []int32{
	0, // 0: redirect.RedirectService.ResolveCode:input_type -> redirect.ResolveCodeRequest
	1, // 1: redirect.RedirectService.ResolveCode:output_type -> redirect.ResolveCodeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_redirect_proto_init() }
func file_redirect_proto_init() {
	if File_redirect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redirect_proto_rawDesc), len(file_redirect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redirect_proto_goTypes,
		DependencyIndexes: file_redirect_proto_depIdxs,
		MessageInfos:      file_redirect_proto_msgTypes,
	}.Build()
	File_redirect_proto = out.File
	file_redirect_proto_goTypes = nil
	file_redirect_proto_depIdxs = nil
}
