{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "urls created",
   "type": "timeseries",
   "description": "number of urls created in shortener service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "shortener_urls_created_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "redirect url cache hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "redirect_cache_hits_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "gateway http requests",
   "type": "timeseries",
   "description": "Total number of HTTP requests for the gateway service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "gateway_http_requests_total", "legendFormat": "__auto" }
   ]
  }
 ]
}