ALTER TABLE links
    ALTER COLUMN created_at TYPE TIMESTAMPTZ,
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,

    ALTER COLUMN expires_at TYPE TIMESTAMPTZ,
    ALTER COLUMN expires_at SET DEFAULT CURRENT_TIMESTAMP;