apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: url-shortener

resources:
  - namespace.yaml
  - postgres-sealed-secret.yaml
  - redis-sealed-secret.yaml
  - gateway/deployment.yaml
  - gateway/service.yaml
  - gateway/configmap.yaml
  # - gateway/secret.yaml  # Replaced with SealedSecret
  - gateway/sealed-secret.yaml  # Add after encrypting with kubeseal
  - gateway/hpa.yaml
  - shortener/deployment.yaml
  - shortener/service.yaml
  - shortener/configmap.yaml
  # - shortener/secret.yaml  # Replaced with SealedSecret
  - shortener/sealed-secret.yaml  # Add after encrypting with kubeseal
  - shortener/hpa.yaml
  - redirect/deployment.yaml
  - redirect/service.yaml
  - redirect/configmap.yaml
  # - redirect/secret.yaml  # Replaced with SealedSecret
  - redirect/sealed-secret.yaml  # Add after encrypting with kubeseal
  - redirect/hpa.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: url-shortener
      app.kubernetes.io/managed-by: kustomize
