apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: url-shortener

resources:
  - namespace.yaml
  - kafka-topics-job.yaml
  - gateway/deployment.yaml
  - gateway/service.yaml
  - gateway/configmap.yaml
  - gateway/secret.yaml
  - gateway/hpa.yaml
  - shortener/deployment.yaml
  - shortener/service.yaml
  - shortener/configmap.yaml
  - shortener/secret.yaml
  - shortener/hpa.yaml
  - redirect/deployment.yaml
  - redirect/service.yaml
  - redirect/configmap.yaml
  - redirect/secret.yaml
  - redirect/hpa.yaml
  - analytics/deployment.yaml
  - analytics/service.yaml
  - analytics/configmap.yaml
  - analytics/secret.yaml
  - analytics/hpa.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: url-shortener
      app.kubernetes.io/managed-by: kustomize
