---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: url-shortener
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    mongodb-metrics-password: AgBYnwNP/mQVxWJIYPcsiQCbLQdAU1kIObjULRxi36BxzoM/mJAikISBs33nOOFs67grvgUYml4xs+tJ2pRoMmm5qw4sgKP2D88FHjZQrTDXne82DCax/pl46HGF7BoD7U4dDmLdLsLUAcSdreawoxbOvYS5iyC1g5ptOc/b5ssZmZf+ugjnDahzfly9gkSi162UR2za0zDQFwlzWDcU0eTHDGL+Fk2h4pc4qNCJoRxpgFQebkJJ6tt3KI4ZC5o48kgVj9VCCipYXC0WXpTCP01VrsOa0IkHh8wygbvAWGxbTF1zKGwQFu76bNtWxxOCsPjDNlYcauz7kp9/n6v4nM0bpw2DK5ApBT4zgoGHwp8o2t3D6raSo2It6HJzS3WPZ3f+EvgSCXKcj5UQ5MXQyB0D+9scz/J963uUjzmSshZons8Fzpw0LAlbB/bYA5Y+Ub2X/6qk+jj2TG2X9pTO8RJNwYLP6Un17QOSbWHPKy5Gj9tJYTP/sK0oxMNV+5YnuQGgSZgKGc8Wq0LIjta7Q6MyqUkzFFa5SpNlx6SwoN2ddy3s0uZSYTZO2nmFVx4/zw7PKoPbHDoylYtTW2r3rgB27WE2vqDnQu2ykFzQMJ9uJqXLkH5/r35S2ppbYo/JG0pmUrHmjTe7TxlUuciI7nY0AA+IgjsdhqSprCzHrEiiAwp4vXZNJUQqmJOlrakYCT+HxpryTw==
    mongodb-root-password: AgCR5S5uIop+mrAniOA1PlIMLBb7NwtZSKDo2NdMfKPHEUJ/MLWHlQ1Ljh3hJh9c6XtFxMt3JuNIuy1/Srf1px5JbUaEuOVlftWOX2+sr3ZPEsNxEVlojfQTTR8JNxhCdmncavgjt/HgPIf7sbWYd+agK4ngH14d6/O8WOctSiu089sUE842fgO+nDlDDwkvAQsFhQvlHYsIgl//aKqN0kVRqtvdrT/WLkM1ZpXfb/xcXRjXDNIGq7aCQqF8rCsIxEaXeveNNvrsoQZYLa9o9NsoFjS4XyLrHQtIDAUbAZ6GxbLr0xVFMDFr06xcBrGbWGhrKRkiHw3ctspZbOL83VhykpB2yk0vq2lsXQQrmbPwMcr80wrY7kzvufOp7kqNMUHN4vGqtyxV51T2C2xdgyq/VtAApCAahtI9MCjJHLmOfNs2eHd9Q99YQKehrpd4mY06CNbpUkQ73HYBjxpBXpwlP+0NEHXGjBEWt6lADJZkIah6hrxOs2gDaxBGWuTcjj6czuTiyYineGAb6PADzkB+axeAFLBmZFhVz9TLZwM+E5Hf62XVoRonuvYAW5EgUXgnsOWXdsAKEJqvAs5MIdoKu8SMU08fJn/i4qlF5KqERXQoqw8hWcAwSK4i/wlFP+OJy3uqrGEQwDGSEfQHS4DJdWJEPWFflCYeMLbA49qdyTLgb/TKIVnyv+uvpVJibtpF+aQi4g==
  template:
    metadata:
      name: mongo-secret
      namespace: url-shortener
    type: Opaque
