---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: url-shortener
spec:
  encryptedData:
    root-password: AgCWhpdwxA1kuo6HWXWxjTb65P5u1WjwRbpFc8FisszMmV0JW6SXzVaD+GyZ9f5uleu5/6qJh69fyNRB9iEEgncwfjXs2ilufUXJVq8+rH8/0rrRDwSQJa5pyAAkfZTEph+bTUuQUcppSsXcRTBkCaehHvntmSscc7CcwwfheZ7mAFMQpOiruaQd2lDhqmTzD+MSjrOmL4CKdqeOpt0l4HhuOhR0l1EHv/TPhdhdfaQN+LVzOxa5YNJ/YPvmpQMwMQaRS3uzquC1ztncpEnF5pZ5ol2W5UvVUe5+7P7Y/BOZpWOwvKrrjuBdL0cCEIC4Oe+X1MP4eiVB9/9/zJHMoqupA0XCQjXzf0hRoKuY0r+/3pOTVNpch6bdC4WD/jkzpfyJzU+4PppoERQllSsc+AcPmSYYBR/x/bPnrePLrMs9jk24Jsl3K4ucrsUsRZtkStdNVX58QdZmW27RohhdqPweZdFoNH9HGtiOQyO/bvjGwQHfIzeN2rioOjmdfF717P5L70+mpJ8ChEH9Wr+XKe8XbfjGAqZ8nCnh0iSNk1zY1PgkngI1bv0NXWGgDZlnT5m6hCnCCrOUUlWb6Di63qxR15WeM0wkl0bRbdtCklVLIbiVjrgB9X4lPPAK/uTghAFWe9ryWe0U7J+ZrvJg6/Ap1x3B31qDk8+VelA/cHETqSd0flz2PyPvklOauCWgoC3U/oAdgg==
  template:
    metadata:
      name: mongo-secret
      namespace: url-shortener
    type: Opaque
