---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: url-shortener
spec:
  encryptedData:
    password: AgAIM5nIyTyIobmQFm/pbUMww+EjuRBh15BZuXmQ/0WlRQZugyXUjXAUOzh7dQj80fB/c6BqXy4z5kZOCjTQU6dYlPUtUqbkQI6ERq3voIX1OxZq9OxK/0iaYqi4Pikxhp37IknIuf98vHpHpa3Ev8c7NciprrS1saua6iMWGrEC3s5LgshhwL3O4HXbxicquxHDuLTO5LLgjleR/zgwWpLKNHIRcZ6ri1iZ5pY2N4r1+WTZ6wefkxkX1JlJgfQpILPI2pqDu+32L/tuy//JxiOVOjDZaOGujy4CTb+dithDvhwS3cdE+P8+BmCWKw1lQHnUk2THb9BM3mfIhH/tIeoz2WRylam62MwWY8ctTXeW+YbMzAZgNTDDMC3qkrxgJd/UK2YFZaXm2H3+ZpoFt0SvG4p5qcyDYOQNjxokPkM20YPqAYeg1UuLyOZmZdAMKFbk8ihXTBMtRj0h/wDeCjE2LNx4+jnrdQSD6sMBk3GkQtyK+jkgnh9NDRS1vfl3kNfGbtGpGMHyegePGs1uWsXVjsjCKMIuHdpbnZ1keY+phDBFgA4cSROIUTt0PDiNUNzAZNtpFM/aumUJTWsxJRgvjOnp8pPM5700Osb4iA+D39pDv7fb1Drqmb7NQoqzNuWElf6O2orM+hzAkXu0BcJVEzHk1tIx0l+K1WN2QzLE/8qpK08QBDs4/32E/Hl5YsUl9Nys1kxb
    postgres-password: AgC0+hrEcA/osgV2zQLd82jWaFPxjp/ZNe5GhbgPYzTz4Dj7QmYcrkg5ETpikNsVNZH/SaWzURoGF+MuwkSY/+TDP1KXUfIjFnk8bvDvHfh5EnKen/YmNgCFPTmdNmrrDrmhEJAnJMpd0BwgI9jUBfnkdfN61VY5+7gyfxH5doZZN78gWnxI62OY2JmjEICsMK9nUB28XCu5Hm4ulgf1teWvg1/LCFpMtcLuRe8lD7SShd7vSIW206x84BauO3762f2b9jeVSn/3ftVR3gknZwqEstkBvLr0Eb7/xC1Ht19qUU0Ih1/ONJmxC2J0/y6T3Fktk7huUe+jKwQKStcGCY4WBbN0+7yzEi8JFnbT61/BMRhiDOjfUaH61YtNJYj66jbVtQTTNaxkfVIbsR2QLu7x6jFoOD9USac9dHDZKnnL7MrGYstarSEKXt0Vq2TMDtRyXLtA7x4okmhdiSElgJl5OB1jiGU9bXCsyaWiA2oQj8XsCFJAg7j0tE4dzLo+ss4L968QLyXgHJYAy82qsbna/v846lhnB9czKALvqM/qDAYh1BIKYmfg3TMrbHT33Cu9CvgpVs6fbgH+sq+o/DWcNpzO8SV2XonRj+TQ5UVEdKJ8OIxeDJqzPrxsCTxcR09wQprHTUSIQIF0FoR/64DBzG2gwSuqfO6dwv5i/I7qzPTJl9gfyXASEBkchMbiYvQrBCRyJVjM
  template:
    metadata:
      name: postgres-secret
      namespace: url-shortener
    type: Opaque
