// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type Link struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Code        string
	OriginalUrl string
	CustomAlias *string
	ExpiresAt   *time.Time
	IsActive    bool
	CreatedAt   time.Time
}
