// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"
)

const findByCode = `-- name: FindByCode :one
SELECT id, code, original_url, user_id, custom_alias, expires_at, is_active, created_at FROM link
WHERE code = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) FindByCode(ctx context.Context, code string) (Link, error) {
	row := q.db.QueryRow(ctx, findByCode, code)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OriginalUrl,
		&i.UserID,
		&i.CustomAlias,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
