fullnameOverride: kafka

controller:
  replicaCount: 1
  persistence:
    enabled: true
    size: 2Gi
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    fsGroupChangePolicy: Always

broker:
  replicaCount: 0

listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT

networkPolicy:
  enabled: false
